//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "listings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub auction_id: i32,
    #[sea_orm(column_type = "Decimal(Some((10, 2)))")]
    pub base_price: Decimal,
    pub available_volume: i32,
    pub deleted_at: Option<DateTime>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::auction_results::Entity")]
    AuctionResults,
    #[sea_orm(
        belongs_to = "super::auctions::Entity",
        from = "Column::AuctionId",
        to = "super::auctions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Auctions,
    #[sea_orm(has_many = "super::bids::Entity")]
    Bids,
}

impl Related<super::auction_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuctionResults.def()
    }
}

impl Related<super::auctions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Auctions.def()
    }
}

impl Related<super::bids::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bids.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
